Overview
--------
This workbook is a companion to https://www.llewellyn.com/product.php?ean=9780738734699[_Taming the Drunken Monkey: The Path to Mindfulness, Meditation, and Increased Concentration_] (C) 2014 by William L. Mikulas, PhD. Without the source text, this workbook will make little sense.

Mastery of the mind will improve all areas of one's life. 

There are five areas of development:

. Concentration
. Awareness
. Mental Flexibility
. Attitude
. Breathwork

Developing concentration will help you focus your attention, control your thoughts, and quiet your runaway mind. Developing awareness will help you have broader and clearer awareness of your body, feelings, thoughts, and the world around you. This awareness will lead to more choice, control, and freedom. And developing flexibility will increase creativity and free you from many mental blocks and biases. You will perceive and think more clearly and freely. Breathwork helps improve the health of the body and mind, helps relax the body and can become an object of attention and awareness.

The book is divided into five levels of proficiency:
[upperroman]
. Novice
. Student
. Warrior
. Adept
. Master

This is a **work**book not a think-book. It is important to do these practices and not just think about them or say "another time, I'm too busy right now". All the time spent developing these skills you will get back many times over.

Enjoy the journey.
