<<<
[[novice]]
Novice
------

[,S Suzuki,"Zen Mind, Beginner's Mind"]
____
In the mind of the beginner, there are many possibilities. In the mind of an expert, there are few.
____

At the novice level, the rules of the game are established and basic instructions to the practices are outlined. Develop habits which establish practice time, place, and form.

Breathwork I
~~~~~~~~~~~~
Observe how you breath. Pay attention to the rising and falling of the abdomen.

Assignments:

* [ ] Spend one or two training sessions observing the movement of the diaphragm.
* [ ] Spend a week of practice time just quietly observing the complete breath.

Moving on:

* [ ] You can easily observe all stages of complete breathing, including the nose, chest, and diaphragm or stomach.
* [ ] You can feel the difference between chest breathing and diaphragm breathing, and periodically intentionally shift from chest breathing to diaphragm breathing.

Awareness I
~~~~~~~~~~~
As you progress through this book, you will gradually become more and more aware: more aware of your body, feelings, thoughts, and mental processes;footnote:[Four Foundations of Mindfulness.] and more aware of other people and the world around you. This awareness will bring you more health, happiness, choice, and freedom.

Assignments:

- [ ] Answer awareness questionnaire.
- [ ] During breathwork, put your emphasis on gradually become more and more aware of the fine aspects of breathing. Put your attention on the breath at the tip of the nose.
- [ ] Put your attention on the rising and falling of the abdomen/stomach. Encourage yourself to become more and more aware of the body related to breathing.
- [ ] Follow the whole cycle of breathing from the air coming in to the air leaving the body. Be aware of pauses and feelings.
- [ ] Body scan at least once a day, five times a week for a few weeks.

Moving on:

- [ ] You understand what awareness is and how it differs from thinking and reacting. 
- [ ] You have spent considerable time learning to become more aware of your breathing and body, and are now much more aware of these than you were when you began.

Concentration I
~~~~~~~~~~~~~~~
Concentration is the ability to keep the mind focused on one thing. Concentration training at the Novice levels begins by keeping the mind focused on the breath.

Begin by relaxing and then sitting or lying quietly observing your breathing. Next, put your attention on your breathing, either at the tip of your nose or the rising and falling of diaphragm or stomach. Breathe naturally and don’t be concerned about how well you are breathing or how aware you are of the breathing; now it is time to emphasize concentration. Now, focus your mind on your breathing. As soon as you are aware that your attention has left your breathing, gently and firmly bring your attention back to your breath. That is all you need to do!

Assignments:

- [ ] Practice concentration training for a few weeks.
- [ ] Combine breathwork, awareness, and concentration training into one practice. Your focus will move from one breathing area to another. But wherever your focus is, whenever your mind leaves the breath, you gently and firmly bring it back.

Moving on:

- [ ] You know the difference between when your mind is focused and when it is not.
- [ ] Even though your mind still jumps around during most practice sessions, you periodically have experienced short periods of time where your attention stayed on the breath.

Attitude I
~~~~~~~~~~
Attitude is the mental set with which one approaches situations. Attitude includes moods, associations, expectations, and intentions.

_Act with Intention_. This means to do the exercises within the book, not just read and think about them.

_Have Fun_. Relax into the journey and enjoy it.

Assignments:

- [ ] Intentionally do the exercises at the Novice level.
- [ ] Reflect on the suggestions related to attitude, and realize that whatever your current attitude, it can be improved in ways that will help you.

Moving on:

- [ ] You have completed the exercises at the Novice level.
- [ ] You have reflected on how to have more fun with the practices, the journey, and life in-general.

Flexibility I
~~~~~~~~~~~~~
With the mental flexibility exercises you will learn to think better and more creatively. There are two aspects to increase mental flexibility.

_Lateral Thinking_. The purpose is to generate new ideas. Think outside the box of correctness. Ways: generate to meet a quota of new ideas, start with the goal and work backwards, brainstorm, random simulation, question assumptions, break concepts into parts, use analogies, and challenge categories and labels.

_Mistakes and Being Wrong_. Making mistakes is often the best and fastest way to learn. Too much avoiding of mistakes can impair mental flexibility. And in regards to being wrong, mental flexibility is improved by being open to the fact that you will periodically be wrong, not being bothered by this fact, and being quick to admit when you are wrong.

Assignments:

- [ ] Make up three more strategies for lateral thinking.
- [ ] Be on alert for times when you are wrong. Seek opportunities to admit when you are wrong.
- [ ] Answer the Mental Play questions at the end of the chapter.

Moving on:

- [ ] You understand the nature of lateral thinking, and you periodically utilize lateral thinking type of strategies. 
- [ ] You have systematically applied lateral thinking to several topics of personal significance. 
- [ ] You are free of the mistake mystique and readily notice and admit being wrong. 
- [ ] You have identified at least one major area where you were wrong and did something to make corrections.

