<<<
[[student]]
== Student
You have the basics in five general areas (concentration, awareness, breathwork, flexibility, and attitude) and now it is time to further hone these skills and build on them. Always remember the following: Learning to use your mind more effectively is one of the most important things you can do with your life; it will improve almost everything you do, and thus increase your happiness and health. To do this, you as a student must spend time developing skills--reading, thinking, and wishing will not work. Whatever time you spend developing these skills you will get back many times over for many reasons, including being more effective and efficient, and avoiding common traps.

=== Concentration II
You continue the same basic practice that you already know: you put your attention on something, such as your breathing at the tip of the nose, and every time the monkey runs off, you gently and firmly bring your attention back to your breathing. For the duration of your concentration practice at the student level is one simple principle: No matter what arises, treat it as a monkey trick and return to your breath. This includes all feelings, images, thoughts, and memories. The primary goal for level II concentration is the further development of one-pointed concentration despite distractions, and using the breath and other objects of focus.

Assignments:

- [ ] What you need to do as a student is add at least two or three new objects of concentration to your practice.
- [ ] Practice _Moment-to-Moment Concentration_. Let your mind go where it will; you let go and don’t choose. But wherever your mind goes, you try to bring to that object concentrated focus.

Moving on:

- [ ] You understand the tricks the monkey uses on you, and although it still periodically catches you, you don’t stay caught long. 
- [ ] Distractions to your concentration periodically arise, but most of the time they are short lived and not troublesome. 
- [ ] You have a clear sense of how to concentrate your mind, and can usually easily do it, when you are aware and motivated. 
- [ ] There have been many times in which you have maintained strong concentration on some object. 
- [ ] You have developed concentration using your breath as well as other objects.

=== Awareness II
At the novice level, awareness of the body was the major object of attention. Awareness of your body should always be part of your practice. From now on you should periodically intentionally focus your awareness on some part of your body,

At the student level, awareness of feelings is added. There is an interrelationship between body, feelings, and mind. Feelings in the body often precede actions and thoughts. Perceptions and thoughts often cause feelings in your body.

NOTE: Body +<--->+ Feelings +<--->+ Mind

Assignments:

- [ ] Intentionally try to clearly notice wherever your mind goes. Try to see clearly whatever arises in your mind, including feelings, perceptions, and thoughts.
- [ ] Experiment with the use of labels.
- [ ] Combine concentration and awareness training.
- [ ] After practicing awareness III for awhile, re-take the awareness questionnaire.

Moving on:

- [ ] You have become more aware of your body in a variety of ways and regularly, consciously attend to some parts of your body. 
- [ ] You have learned how to cultivate awareness during your way of practice. 
- [ ] You know the difference between awareness and concentration. 
- [ ] You can easily be aware of how concentrated your mind is. 
- [ ] You are becoming more aware of how aware you are at any time.

=== Attitude II
_Make Friends with Yourself_. Unconditionally accept yourself, even when you are recognizing areas for improvement. If you say you can’t accept yourself unconditionally, then accept yourself as someone who can’t accept her or his self unconditionally.

_Be in the Here and Now_. The key to bringing yourself into the here and now is concentration, with help from awareness. When you are aware that you are lost in the past or future, you concentrate on something in the present to bring you back to the here and now.

Assignments:

- [ ] Reflect on how the four components of attitude be applied to many aspects of your life.
- [ ] Reflect on the four components at least once a week, then once a month, and then periodically.

Moving on:

- [ ] You are continually discovering new ways attitude applies to your life and finding more and more depth and subtlety to your understanding.

=== Breathwork II
At the student level you will learn how to further refine and alter your breathing by changing the rate of inhalation and exhalation. You will also learn additional ways to use breathing to reduce stress and anxiety.

You want to exhale when you are contracting, bending forward, compressing your stomach, or twisting. You want to inhale when are expanding, bending backward, opening your chest, or coming out of a stretch.

When you want to relax more, lengthen the time of exhalation and briefly hold your breath after exhaling. If you are feeling anxious, gradually lengthen the time of exhalation. If you need more energy, lengthen the time of inhalation and briefly hold your breath after inhaling.

Some cases of fatigue are helped by first lengthening exhalations for about a dozen breaths and then gradually lengthening inhalations. And some cases of depression are helped by having the same length of both inhalation and exhalation, and then gradually lengthening both.

Assignments:

* [ ] Observe how long it takes you to inhale versus how long to exhale.
* [ ] Spend a week of practice time just quietly observing the complete breath.

Moving on:

* [ ] You periodically monitor your breathing in various situations and alter it as needed. 
* [ ] You have added to your overall awareness of your complete breathing the periodic awareness of the relative lengths of inhalation and exhalation. 
* [ ] You have learned how to alter these lengths for the purpose of relaxation or energy.

==== Relaxing
A simple way to relax is to use the 4-2-4-2 controlled breathing technique. Here you gradually inhale for a count of four, hold your breath for a count of two, gradually exhale for a count of four, hold your breath for a count of two, and then begin again.

Relax by imagining a pleasant scene. Practice this with imagined situations that cause negative emotions.

Moving on:

* [ ] You have developed your own powerful way to relax using breathwork, such as deep breathing and/or 4-2-4-2 breathing. 
* [ ] You have used this relaxation practice many times in real life situations. 
* [ ] You are continually becoming more aware of bodily cues related to how relaxed you are and changes in this relaxation. 
* [ ] You understand and appreciate how concentration, awareness, and breathwork combine to relax body and mind.

=== Flexibility II
Increasing mental flexibility increases creativity.

Question assumptions such as long held ideas and habit patterns. 

Moving on:

* [ ] Rather than just unconsciously wandering through life, as a student you periodically reflect on, and occasionally question, some of your habitual perceptions, thoughts, values, and actions. 
* [ ] You have made some important changes in some of your ideas, and you have found better ways of doing some things. 
* [ ] Complete mental play puzzles.
