<<<
[[adept]]
== Adept
At the adept level you will come to appreciate more how everything is interrelated.

=== Concentration IV

Adept concentration is based on the understanding that any situation is an opportunity to further refine one’s concentration. Thus, every situation is a chance to do one or more of the following: be aware of how concentrated your mind is, actively quiet and focus your mind more, and keep your attention focused.

The level is also an opportunity to further refine Moment-To-Moment Concentration (MTMC).

Assignments:

- [ ] Read through the Awareness Questionnaire and consider how both concentration and awareness apply to what is being asked.

=== Awareness IV

Awareness training at the adept level is based on the fact that every situation is an opportunity to develop awareness.

. Create the time and space to do just one activity. Do not combine activities or multitask.
. Do the activity slowly.
. Take your time, be aware, and enjoy.

Assignments:

- [ ] Eat a meal with complete awareness, slowly, and by yourself. Then, wash the dishes with awareness.
- [ ] Everyday pick at least one activity to do with full awareness and concentration.
- [ ] Increase the number from one activity to several activities.
- [ ] Set aside a half day to do everything with complete awareness.
- [ ] Set aside a full day to do everything with full awareness.
- [ ] After practicing awareness III for awhile, re-take the awareness questionnaire.

==== Awareness of Pain

Working with pain is one way to brings one focus into the here and now of direct experience.

. Notice the experience of being fully in the here and now.
. Try to bring your awareness to the simple sensation of pain, the pure sensation before you label it “pain” or respond to it in any way. Bring your awareness to the direct contact with the sensation.

==== Sitting Practice

It is important to continue to develop awareness during your way of practice, such as sitting and watching your breath.

. Notice how your body and mind interact.
. Focus on the rising and falling of events in your consciousness.

==== Awareness While Walking

You can cultivate concentration and awareness while walking in the same way you cultivated them during sitting.

Slow formal walking. Cultivate awareness as described in this whole awareness section. Concentration is developed by continually bringing your attention back to walking. At first, do this for ten to fifteen minutes and then longer.

Walk at other speeds.

Put attention on breath while walking.

=== Attitude III

Continue to reflect on the four aspects of attitudes that were introduced at the first two levels. The warrior sees how these are applicable to all of living, not just mental training.

* Have Fun
* Act with Intention
* Make Friends with Yourself
* Be in the Here and Now

_Time-Outs_: Take periodic time outs and days of rest. In addition, go off on retreats.

Assignments:

- [ ] Continue to reflect on the four aspects of attitude.
- [ ] Take increasing amounts of time-outs.

=== Breathwork III
You will learn here optional breathwork mental practices from pranayama.

_Purifying Breath_: Inhale fully with a deep breath and then exhale most of the air. At the end of the exhale, stop, then exhale a little more, stop, exhale a little more, stop, exhale a little more...Do this until you can’t exhale any more. All of this is one purifying breath. Do three purifying breaths in a row.

_Vitalic Breath_: First, breathe in through the nose with a series of sharp sniffs until the lungs are completely full. Then, blow out sharply through the mouth with a loud “HAAA.” Do this vitalic breath three times in a row.

_Alternate Nostril Breathing_: The complete alternate nostril breathing consists of this cycle: 

. Slowly take a deep breath inhaling through your left nostril for a count of 4.  
. Hold your breath for a count of 4.
. Slowly and completely exhale through your right nostril for a count of 8.  
. Slowly and deeply inhale through your right nostril for a count of 4.
. Hold for a count of 4.
. Slowly and completely exhale through your left nostril for a count of 8.  

Do five to ten of these cycles of alternate nostril breathing, pausing between each cycle, while letting your breathing flow naturally.

Assignments:

* [ ] Practice purifying breathing.
* [ ] Practice vitalic breathing.
* [ ] Practice alternate nostril breathing.

=== Flexibility III

Flexibility at the warrior levels involves looking at attachments, meditation, and mental play.

==== Attachments

Attachments are obstacles to mental flexibility. Attachments are bad and lead to suffering. Being a warrior includes the willingness and desire to be in the world in the midst of attachments, confronting and reducing them. Sometimes this is difficult, but the warrior is up to the challenge. Attachments are the grist for the mill, opportunities for significant personal and spiritual growth.

Attitude: take delight in discovering an attachment. Make friends with yourself.

Awareness: First, notice the results of an attachment such as an undesired emotion. Then, go back in time to see if you can identify the attachment which was the cause.

Action: What do you do to reduce the attachment.

- [ ] Identify a wide range of attachments at play in your life.
- [ ] Write them down
- [ ] Devise a plan to reduce the important ones

==== Meditation

The practice of meditation consists of four components: 

1. Form
2. Behaviors of the mind
3. Attitude
4. Object

Your training in concentration and awareness will strongly help you in many of the world's spiritual traditions. If you are at the Warrior level, you already have advanced skills for meditation in all of these traditions.

==== Mental Play

The playful warrior recognizes that having fun is not only pleasurable but also good for the health of body, mind, and spirit. The warrior brings the attitude of having fun to as many activities as possible. The warrior looks for and creates many opportunities to play. And the warrior understands playtime as a time to be in the here and how, a time to be free and open to novelty and surprise, and a time for creativity and lateral thinking.

The world's best non-gambling strategy games:

* Chess
* Go
* Duplicate Bridge

Warriors find games that they and various friends enjoy. Most important, warriors enjoy playing with all aspects of living with all of its interesting challenges.

- [ ] Learn a new game (chess, go, or bridge).
